<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_cleverreach"
 *
 * Auto generated by Extension Builder 2015-02-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cleverreach Newsletter mailer',
	'description' => 'Use your own page layout as a newsletter template. Let the editors do their job, like working on the regular website. After finishing editing the page let them choos the receiver group, set a subject and give it to Cleverreach via APi. You just have to login to Cleverrach to do the final sendout as the API is limited to do this.',
	'company' => 'Pil ink',
	'category' => 'module',
	'author' => 'Lukas Jakob',
	'author_email' => 'lu.jakob@googlemail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);